# Gitpod configuration
image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      # heavy lifting that gitpod executes on each commit
      # https://www.gitpod.io/docs/config-start-tasks#prebuild-and-new-workspaces
      # setup foundry forge locally
      sudo curl -L https://foundry.paradigm.xyz | bash
      sudo source /home/gitpod/.bashrc
      sudo foundryup
      sudo make install
      # build source and run tests
      make build
      make test-unit-all
